### ISSUE TITLE
hpSettingsChanged() not called

### ISSUE THREAD

**Issue by salas81** [SwiCago/HeatPump#94]
I'm trying your example code to control the AC unit over MQTT. It doesn't seem to me that the hpSettingsChanged() callback is called, when for example I change the settings with the remote. Is that supposed to be that way? When should it be called?  This is the log of the MQTT traffic on the debug topic

US-IT00103-2:~ lorenzo.decaria$ mosquitto_sub -h raspberrypi.local -t heatpump/debug

{"packetSent":"fc 5a 01 30 02 ca 01 a8 "}
{"packetRecv":"fc 7a 01 30 01 00 54 00 1c 06 ff 3f dc 06 10 40 5f f3 fe 3f 00 00 "}
{"packetSent":"fc 42 01 30 10 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 7b "}
{"packetRecv":"fc 62 01 30 10 02 00 00 01 01 1a 05 00 00 00 03 ab 00 00 00 00 8c "}
{"packetSent":"fc 42 01 30 10 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 7a "}
{"packetRecv":"fc 62 01 30 10 03 00 00 0a 00 00 a8 00 00 00 00 00 00 00 00 00 a8 "}
{"packetSent":"fc 42 01 30 10 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 79 "}
{"packetRecv":"fc 62 01 30 10 04 00 00 00 80 00 00 00 00 00 00 00 00 00 00 00 d9 "}
{"packetSent":"fc 42 01 30 10 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 78 "}
{"packetRecv":"fc 62 01 30 10 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 58 "}
{"packetSent":"fc 42 01 30 10 06 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 77 "}
{"packetRecv":"fc 62 01 30 10 06 00 00 09 01 00 00 00 00 00 00 00 00 00 00 00 4d "}
{"packetSent":"fc 42 01 30 10 09 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 74 "}
{"packetRecv":"fc 62 01 30 10 09 00 00 00 01 01 00 00 00 00 00 00 00 00 00 00 52 "}
{"packetSent":"fc 42 01 30 10 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 7b "}
{"packetRecv":"fc 62 01 30 10 02 00 00 01 08 1a 00 00 00 00 03 ab 00 00 00 00 8a "}
{"packetSent":"fc 42 01 30 10 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 7a "}
{"packetRecv":"fc 62 01 30 10 03 00 00 0a 00 00 a8 00 00 00 00 00 00 00 00 00 a8 "}
{"packetSent":"fc 42 01 30 10 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 79 "}
{"packetRecv":"fc 62 01 30 10 04 00 00 00 80 00 00 00 00 00 00 00 00 00 00 00 d9 "}
{"packetSent":"fc 42 01 30 10 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 78 "}
{"packetRecv":"fc 62 01 30 10 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 58 "}

**Comment by SwiCago** [comment]
It might be firing, but mqtt is dropping it, as there is not enough chars available to send the json. See the not in the .h file in regards to  PubSubClient.h  
Also, since this is a new issue, I assume your prior issue #93 was due to user error. Would have been nice to comment and close! I am also going to assume this to be a user issue and not a library issue, as you are the only one, where this is not working. I am going to close this now. Please use the gitter chat going forward. It is linked on first page, but I'll link it here too https://gitter.im/Mitsubishi-Heat-Pump
There are a lot of good people that can help in that chat, before issues are opened. Issues should only be opened, if there is without a doubt an issue with the library or to collaborate on a new idea.
